<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="DTOs\Auth\" />
    <Folder Include="DTOs\Category\" />
    <Folder Include="DTOs\Cart\" />
    <Folder Include="DTOs\Order\" />
    <Folder Include="DTOs\Wishlist\" />
    <Folder Include="DTOs\Product\" />
    <Folder Include="Middleware\" />
    <Folder Include="Helpers\" />
    <Folder Include="Repositories\Interfaces\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
